"""
          EDA VISUALISATIONS - Bank Churn
Goal: visually explore features against the target variable
(churn: yes/no)

Outputs: eda_numeric.png + eda_categorical.png

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('bank.csv', sep=';')

# Convert target to binary for easier rate calculations
df['churn'] = (df['y'] == 'yes').astype(int)
print(f"Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns")

# Visual settings
# Consistent palette throughout: green = non-churner, red-orange = churner
palette = {'no': '#1D9E75', 'yes': '#D85A30'}
colors  = ['#1D9E75', '#D85A30']

sns.set_theme(style='whitegrid', font_scale=0.9)
plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor':   '#F8F9FA',
    'axes.edgecolor':   '#DEE2E6',
    'grid.color':       '#E9ECEF',
    'font.family':      'DejaVu Sans',
})


# FIGURE 1 - Numeric features vs Churn

fig1, axes = plt.subplots(3, 3, figsize=(15, 12))
fig1.suptitle('EDA - Numeric Features vs Churn', fontsize=14, fontweight='bold', y=1.01)

# 1.1 Target distribution
# Visualising the class imbalance upfront is critical:
# a strong imbalance (~88/12 here) affects the choice of metrics
# and resampling techniques (SMOTE, class_weight, etc.)
ax = axes[0, 0]
counts = df['y'].value_counts()
bars = ax.bar(['Non-churner\n(no)', 'Churner\n(yes)'], counts.values,
              color=colors, width=0.5, edgecolor='white')
for bar, val in zip(bars, counts.values):
    pct = val / len(df) * 100
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 30,
            f'{val}\n({pct:.1f}%)', ha='center', va='bottom', fontsize=9, fontweight='bold')
ax.set_title('Target Distribution (y)', fontweight='bold')
ax.set_ylabel('Number of Clients')

# 1.2 Age KDE by class
# KDE (Kernel Density Estimate) smooths the distribution like a continuous
# histogram. Overlaying both classes shows whether age discriminates.
ax = axes[0, 1]
for label, grp in df.groupby('y'):
    grp['age'].plot.kde(ax=ax, label=label, color=palette[label], linewidth=2)
ax.set_title('Age by Class', fontweight='bold')
ax.set_xlabel('Age')
ax.legend(title='Churn')
ax.set_xlim(15, 90)
# Churners tend to be slightly older

# 1.3 Balance KDE by class
ax = axes[0, 2]
for label, grp in df.groupby('y'):
    grp['balance'].plot.kde(ax=ax, label=label, color=palette[label], linewidth=2)
ax.set_title('Bank Balance by Class', fontweight='bold')
ax.set_xlabel('Balance (€)')
ax.legend(title='Churn')
ax.set_xlim(-5000, 20000)
#   Balance alone has low discriminatory power, but combined with
#   other features it can still contribute to the model

# 1.4 Call duration boxplot
#   DATA LEAK: this feature is only known AFTER the call.
#   We visualise it here for understanding, but it will be
#   dropped during feature engineering.
ax = axes[1, 0]
df.boxplot(column='duration', by='y', ax=ax, patch_artist=True,
           boxprops=dict(facecolor='#AED6F1'),
           medianprops=dict(color='#D85A30', linewidth=2))
ax.set_title("Call Duration (duration) ! data leak", fontweight='bold')
ax.set_xlabel('Churn')
ax.set_ylabel('Seconds')
plt.sca(ax)
plt.title('')  # remove auto-title generated by boxplot

# 1.5 Number of contacts during current campaign
# Capped at 10 for readability: values above 10 are rare but
# would stretch the axis and compress the main distribution.
ax = axes[1, 1]
df_c = df.copy()
df_c['campaign_capped'] = df_c['campaign'].clip(upper=10)
for label, grp in df_c.groupby('y'):
    grp['campaign_capped'].value_counts().sort_index().plot(
        kind='bar', ax=ax, alpha=0.7, label=label,
        color=palette[label], width=0.4,
        position=0 if label == 'no' else 1)
ax.set_title('Contacts During Current Campaign', fontweight='bold')
ax.set_xlabel('Contacts (capped at 10)')
ax.set_ylabel('Number of Clients')
ax.legend(title='Churn')
# The more a client is contacted, the less they convert -> sign of fatigue

# 1.6 Churn rate by previous contact history
# pdays = -1 means "never contacted before this campaign".
# We create a binary variable here to visualise its impact on churn.
ax = axes[1, 2]
df['contacted_before'] = (df['pdays'] != -1).map(
    {True: 'Previously Contacted', False: 'Never Contacted'})
churn_by_contact = df.groupby('contacted_before')['churn'].mean().reset_index()
bars = ax.bar(churn_by_contact['contacted_before'],
              churn_by_contact['churn'] * 100,
              color=['#5DADE2', '#F0A500'], edgecolor='white', width=0.4)
for bar, val in zip(bars, churn_by_contact['churn'] * 100):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
            f'{val:.1f}%', ha='center', fontsize=9, fontweight='bold')
ax.set_title('Churn Rate: Prior Contact?', fontweight='bold')
ax.set_ylabel('Churn Rate (%)')
ax.set_ylim(0, 25)
# Clients previously contacted in a past campaign churn more often

# 1.7 Correlation heatmap
# Shows linear correlations between all numeric features.
# Useful to detect redundancies (multicollinearity) and identify
# variables most linearly related to the target (churn).
ax = axes[2, 0]
num_cols = ['age', 'balance', 'duration', 'campaign', 'pdays', 'previous', 'churn']
corr = df[num_cols].corr()
sns.heatmap(corr, ax=ax, annot=True, fmt='.2f', cmap='RdYlGn', center=0,
            linewidths=0.5, cbar_kws={'shrink': 0.8}, annot_kws={'size': 8})
ax.set_title('Numeric Feature Correlation', fontweight='bold')
ax.tick_params(axis='x', rotation=45)
#  duration is most correlated with churn (but it's a data leak)
#  previous has a notable positive correlation with churn

# 1.8 Age vs Balance scatter
# If there's no clear separation between the two clouds,
# a linear model will be limited -> justifies non-linear models.
ax = axes[2, 1]
for label, grp in df.groupby('y'):
    ax.scatter(grp['age'], grp['balance'],
               alpha=0.25, s=12, color=palette[label], label=label)
ax.set_title('Age vs Balance by Class', fontweight='bold')
ax.set_xlabel('Age')
ax.set_ylabel('Balance (€)')
ax.legend(title='Churn')
# No clear linear separation -> justifies Random Forest or XGBoost

# 1.9 Previous contacts distribution (previous > 0)
# Filtering out clients never contacted before (previous = 0)
# to focus on those with a contact history.
ax = axes[2, 2]
df_prev = df[df['previous'] > 0]
for label, grp in df_prev.groupby('y'):
    grp['previous'].clip(upper=8).value_counts().sort_index().plot(
        kind='bar', ax=ax, alpha=0.7, label=label, color=palette[label])
ax.set_title('Prior Contacts (previous > 0)', fontweight='bold')
ax.set_xlabel('Number of Prior Contacts')
ax.set_ylabel('Number of Clients')
ax.legend(title='Churn')

fig1.tight_layout()
fig1.savefig('eda_numeric.png', dpi=150, bbox_inches='tight')
print("Figure 1 saved -> eda_numeric.png")


# FIGURE 2 - Categorical features vs Churn

# For each categorical variable, we compute the churn rate per modality
# and compare it to the global average (dashed line).
# More informative than raw counts - directly shows which modality is "at risk".
fig2, axes2 = plt.subplots(3, 3, figsize=(15, 12))
fig2.suptitle('EDA - Categorical Features vs Churn', fontsize=14, fontweight='bold', y=1.01)

cat_features = ['job', 'marital', 'education', 'default',
                'housing', 'loan', 'contact', 'month', 'poutcome']

# Notes per feature:
# job      → retired and students have the highest churn rates
# marital  → single clients churn slightly more
# education→ primary level: higher rate; tertiary: lower
# default  → low impact (very few "yes" cases)
# housing  → mortgage = less churn (more engaged client)
# loan     → personal loan = slight churn increase
# contact  → "unknown" contact mode = high churn rate
# month    → December and March stand out with high rates
# poutcome → 'success' is very predictive: previously converted clients churn less

for idx, feat in enumerate(cat_features):
    ax = axes2[idx // 3][idx % 3]

    # Average churn rate per modality, sorted descending
    churn_rate = df.groupby(feat)['churn'].mean().sort_values(ascending=False) * 100
    bars = ax.bar(
        churn_rate.index, churn_rate.values,
        color=plt.cm.RdYlGn_r(np.linspace(0.1, 0.7, len(churn_rate))),
        edgecolor='white'
    )

    # Reference line = global churn rate
    global_rate = df['churn'].mean() * 100
    ax.axhline(global_rate, color='#333', linestyle='--',
               linewidth=1, alpha=0.6, label=f'Avg {global_rate:.1f}%')

    for bar, val in zip(bars, churn_rate.values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.2,
                f'{val:.0f}%', ha='center', va='bottom', fontsize=7.5, fontweight='bold')

    ax.set_title(f'Churn Rate by {feat}', fontweight='bold', fontsize=10)
    ax.set_ylabel('Churn Rate (%)')
    ax.set_ylim(0, churn_rate.max() * 1.3)
    ax.tick_params(axis='x', rotation=35, labelsize=8)
    ax.legend(fontsize=7)

fig2.tight_layout()
fig2.savefig('eda_categorical.png', dpi=150, bbox_inches='tight')
print("Figure 2 saved → eda_categorical.png")
